// Pure generators for the Android App Actions resources. Kept free of Expo
// imports so they can be unit-tested (see __tests__/appActionsPlugin.test.ts).

const FEATURES = [
  {
    id: 'quick_log',
    deepLinkFeature: 'quick_log',
    label: 'Quick Log',
    longLabel: 'Quick Log a habit',
    synonyms: ['Quick Log', 'Log', 'Log it', 'Log a habit', 'Voice log', 'Record a habit'],
  },
  {
    id: 'habits',
    deepLinkFeature: 'habits',
    label: 'My Habits',
    longLabel: 'See my habits',
    synonyms: ['My Habits', 'Habits', 'Habit list', 'Home', 'Progress'],
  },
  {
    id: 'add_habit',
    deepLinkFeature: 'add_habit',
    label: 'Add habit',
    longLabel: 'Create a new habit',
    synonyms: ['Add habit', 'New habit', 'Create habit', 'Add'],
  },
];

const LOG_HABIT_QUERIES = [
  'log $habit',
  'log $habit done',
  'mark $habit done',
  'record $habit',
  'log $minutes minutes of $habit',
  'log $habit for $minutes minutes',
  'record $minutes minutes of $habit',
];

function escapeXml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, "\\'");
}

function link(scheme, host, query = '') {
  return `${scheme}://${host}${query}`;
}

function buildShortcutsXml({ packageName, scheme }) {
  const target = `android:targetPackage="${packageName}"\n      android:targetClass="${packageName}.MainActivity"`;

  const shortcuts = FEATURES.map(
    (f) => `  <shortcut
    android:shortcutId="${f.id}"
    android:enabled="true"
    android:shortcutShortLabel="@string/app_action_${f.id}_short"
    android:shortcutLongLabel="@string/app_action_${f.id}_long">
    <intent
      android:action="android.intent.action.VIEW"
      android:data="${link(scheme, 'open', `?feature=${f.deepLinkFeature}`)}"
      ${target} />
    <capability-binding android:key="actions.intent.OPEN_APP_FEATURE">
      <parameter-binding
        android:key="feature"
        android:value="@array/app_action_${f.id}_synonyms" />
    </capability-binding>
  </shortcut>`
  ).join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAppActions.js. Do not edit; change the plugin instead. -->
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

  <!-- "Open Habit Tracker quick log" / "Show my habits in Habit Tracker" -->
  <capability android:name="actions.intent.OPEN_APP_FEATURE">
    <intent
      android:action="android.intent.action.VIEW"
      ${target}>
      <url-template android:value="${link(scheme, 'open', '{?feature}')}" />
      <parameter android:name="feature" android:key="feature" />
    </intent>
  </capability>

  <!-- "Find yoga in Habit Tracker" -> opens the matching habit -->
  <capability android:name="actions.intent.GET_THING">
    <intent
      android:action="android.intent.action.VIEW"
      ${target}>
      <url-template android:value="${link(scheme, 'habit', '{?name}')}" />
      <parameter android:name="thing.name" android:key="name" />
    </intent>
  </capability>

  <!-- "Save 20 minutes of yoga to Habit Tracker" -> Quick Log review screen -->
  <capability android:name="actions.intent.CREATE_THING">
    <intent
      android:action="android.intent.action.VIEW"
      ${target}>
      <url-template android:value="${link(scheme, 'log', '{?name,description}')}" />
      <parameter android:name="thing.name" android:key="name" />
      <parameter android:name="thing.description" android:key="description" />
    </intent>
  </capability>

  <!-- "Record 15 minute yoga on Habit Tracker" -->
  <capability android:name="actions.intent.RECORD_EXERCISE">
    <intent
      android:action="android.intent.action.VIEW"
      ${target}>
      <url-template android:value="${link(scheme, 'log', '{?name,duration}')}" />
      <parameter android:name="exercise.name" android:key="name" />
      <parameter android:name="exercise.duration" android:key="duration" />
    </intent>
  </capability>

  <!-- "Open Habit Tracker and log yoga" -->
  <capability
      android:name="custom.actions.intent.LOG_HABIT"
      app:queryPatterns="@array/logHabitQueries">
    <intent
      android:action="android.intent.action.VIEW"
      ${target}>
      <url-template android:value="${link(scheme, 'log', '{?habit,minutes}')}" />
      <parameter
        android:name="habit"
        android:key="habit"
        android:mimeType="https://schema.org/Text" />
      <parameter
        android:name="minutes"
        android:key="minutes"
        android:mimeType="https://schema.org/Number" />
    </intent>
  </capability>

${shortcuts}
</shortcuts>
`;
}

function buildValuesXml() {
  const strings = FEATURES.flatMap((f) => [
    `  <string name="app_action_${f.id}_short">${escapeXml(f.label)}</string>`,
    `  <string name="app_action_${f.id}_long">${escapeXml(f.longLabel)}</string>`,
  ]).join('\n');

  const arrays = FEATURES.map(
    (f) =>
      `  <string-array name="app_action_${f.id}_synonyms">\n${f.synonyms
        .map((s) => `    <item>${escapeXml(s)}</item>`)
        .join('\n')}\n  </string-array>`
  ).join('\n');

  const queryPatterns = `  <string-array name="logHabitQueries">\n${LOG_HABIT_QUERIES.map(
    (q) => `    <item>${escapeXml(q)}</item>`
  ).join('\n')}\n  </string-array>`;

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAppActions.js. Do not edit; change the plugin instead. -->
<resources>
${strings}
${arrays}
${queryPatterns}
</resources>
`;
}

module.exports = { FEATURES, buildShortcutsXml, buildValuesXml };
